---
title: "analysis——isa"
format: html
---

```{r}
library(tidyverse)
sim_data <- readRDS("sim_data.rds")
head(sim_data)
```
```{r}
#creating occams threshold
threshold <- max(results$post_prob) / 20
```

```{r}
#filtering occams result
occams_results <- results %>%
  filter(post_prob >= threshold) %>%
  mutate(post_prob_normalized = post_prob / sum(post_prob)) #normalized the weight 
sum(occams_results$post_prob_normalized)
print(paste("Original number of models:", nrow(results)))
print(paste("Number of models after Occam's Window:", nrow(occams_results)))
#check which models win
occams_results %>% 
  select(model, post_prob_normalized)
```

```{r}
calc_pip <- function(var_name, data) {
  data %>%
    filter(str_detect(model, var_name)) %>%
    summarise(pip = sum(post_prob_normalized)) %>%
    pull(pip)
}

pip_values <- tibble(
  predictor = c("x1", "x2", "x3", "x4"),
  pip = map_dbl(predictor, calc_pip, data = occams_results)
)

# visuals 
ggplot(pip_values, aes(x = reorder(predictor, -pip), y = pip)) +
  geom_col(fill = "pink") +
  theme_minimal() +
  labs(title = "Variable Inclusion Probabilities (PIP)",
       subtitle = "Calculated using Occam's Window",
       x = "Predictors", y = "Probability")
```


```{r}
# ols
ols_model <- lm(y ~ x1 + x2 + x3 + x4, data = sim_data)
summary(ols_model)

```


```{r}

set.seed(123)
n <- nrow(sim_data)

extra_noise <- matrix(rnorm(n * 11), ncol = 11)
colnames(extra_noise) <- paste0("noise_", 1:11)

wide_data <- as.data.frame(cbind(sim_data, extra_noise))

dim(wide_data)
```

```{r}
library(BAS)

mcmc_bma <- bas.lm(y ~ ., 
                   data = wide_data, 
                   method = "MCMC",               
                   MCMC.iterations = 10000,       
                   prior = "BIC", 
                   modelprior = uniform())


mcmc_pip_data <- data.frame(
  variable = mcmc_bma$namesx,
  pip = as.numeric(mcmc_bma$probne0)
) %>% 
  filter(variable != "Intercept") 


ggplot(mcmc_pip_data, aes(x = reorder(variable, -pip), y = pip)) +
  geom_col(fill = "steelblue") +
  theme_minimal() +
  labs(title = "Posterior Inclusion Probabilities (M-H MCMC)",
       subtitle = "Scenario: Predicting Exam Scores with 15 Predictors",
       x = "Predictors", y = "PIP (Probability)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot(mcmc_bma, which = 4, ask = FALSE, caption = "MCMC Model Search Traceplot")
```
```{r}
diagnostics(mcmc_bma, type = "model-probability")


```

